name: 米游社签到

env:
  config_url: ${{ secrets.CONFIG_URL }}

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  Run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 安装环境
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: 获取代码
      run: |
        git clone https://github.com/Womsxd/AutoMihoyoBBS --depth=1

    - name: 安装依赖
      run: |
        cd AutoMihoyoBBS
        pip install -r requirements.txt

    - name: 配置参数
      run: |
        cd AutoMihoyoBBS/config
        wget $config_url
        
    - name: 执行签到
      run: |
        cd AutoMihoyoBBS
        python main.py
        
    - uses: actions/checkout@v2
    - name: 保存参数
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.TOKEN }}
        gist_id: 9916df1d2cff0aff8ec1921131eeed68
        gist_file_name: config.json
        file_path: ./AutoMihoyoBBS/config/config.json
